jep/settings.py

because it is a dev requirement

django_extensions only in debug

---

ephios/event_management/models.py
ephios/event_management/pdf.py
ephios/event_management/templates/event_management/event_archive.html
ephios/event_management/templates/event_management/event_detail.html
ephios/event_management/templates/event_management/event_list.html
ephios/event_management/views.py
ephios/templates/base.html

Ok hear me out on this one. This is about performance. When we have 100 events in the list, we don't want to make queries for every single one of them. But that's what has been happening with start and end times. I now changed start and end time on event to be a getter to make more clear that it does a query. (It was only used in the multi shift pdf export afais).
Then I just used annotate for the two list views.

Event times getter

---

ephios/event_management/forms.py
ephios/event_management/models.py
tests/event_management/test_event_form.py

Editing the `visible_for` on events after people already signed up for shifts is a complicated situation. 
To avoid confusion about why an event became invisible, I propose to force view permissions for participating users.
For now, I opted for allowing *any* state for `LocalParticipation`, which is very much debatable:
* confirmed users should always see the event, as they are involved in it (calendar, date info, notifications etc...)
* requested users should be able to see that they requested a participation. I'd say the same goes for declined and rejected
* We *could* remove the `GETTING_DISPATCHED` state, though I did not bother, since this state probably doesn't exist when editing the event.

Assign event view permissions to participating users

---

ephios/settings.py
poetry.lock
pyproject.toml

together with https://github.com/ephios-dev/ephios-ansible/pull/2
closes #298

add redis caching

---

poetry.lock
pyproject.toml

We had trouble upgrading our production environments:
- the environment existed for a while and had version 1 of a dependency installed.
- dependabot came along and upgraded the dependency to version 2. We installed that in the dev environment from `poetry.lock` and where dependent on features of that update, the requirements in `pyproject.toml` stayed untouched
- on the production environment, version 1 of the dependency was still installed and when upgrading the project with pip, pip's new default upgrade strategy `only-if-needed` didn't upgrade the dependency, because of course it wasn't needed according to `pyproject.toml`. 
- Now the failure occurred: version 1 was installed, but version 2 was required by the project.
This PR now upgrades all requirements in `pyproject.toml` and adds …

Dependency upgrades

---

.github/workflows/staging.yml
.github/workflows/tests.yml

https://github.blog/changelog/2022-08-09-github-actions-ubuntu-22-04-is-now-generally-available-on-github-hosted-runners/
1. switch to 22.04 for testing
2. switch to ubuntu-latest for merge

GH Actions: upgrade ubuntu version, use inbuilt resources

---

.github/workflows/publish.yml
.github/workflows/staging.yml
pyproject.toml

The installation method of poetry-dynamic-versioning has changed in the meantime, resulting in the wheels being built with version 0.0.0

fix poetry-dynamic-versioning installation

---

ephios/core/signup/methods.py
ephios/core/templates/core/disposition/fragment_participation.html
ephios/extra/widgets.py

makes sure that the errors caused by #417 are properly displayed in the disposition form and are not causing HTTP 500 anymore

display timezone errors in disposition

---

ephios/core/templates/core/userprofile_workinghours.html
ephios/core/templates/core/workinghours_list.html
ephios/static/ephios/scss/ephios_custom.scss
tests/core/test_workinghours.py

I can't get the buttons to use the full height of the row while staying on the same line instead of being on top of each other. @felixrindt can you do some CSS magic here?

fix mobile layout for workinghour views

---

ephios/plugins/basesignup/signup/common.py
ephios/plugins/basesignup/signup/coupled_signup.py
ephios/plugins/basesignup/signup/no_selfservice.py
tests/plugins/basesignup/test_no_selfservice.py

I don't know why we did it this way last time. Maybe an error during refactoring. In my opinion, we really don't need the base fields for coupled and no-selfservice signup:
`minimum_age`, `signup_until`, `user_can_decline_confirmed`, `user_can_customize_signup_times`

Remove unused fields from special case signup methods

---

ephios/templates/404.html
ephios/templates/base.html

*The diff looks kinda messed up because of indent.*
In our saas plugin I want to use `base.html` as a base template, but don't want to use the default navigation. I therefore put it in a block to remove it in the child template.

Enable template access to navbar

---

ephios/core/signals.py
ephios/core/views/event.py
ephios/extra/fields.py
ephios/plugins/eventautoqualification/forms.py
ephios/plugins/guests/forms.py
ephios/plugins/simpleresource/forms.py
pyproject.toml
tests/conftest.py
tests/core/test_ical.py
tests/core/test_views_group.py
tests/core/test_views_userprofile.py
tests/core/test_workinghours.py
tests/plugins/simpleresource/test_resources.py

We are getting some warnings in our tests that can be fixed internally. Some remaining warnings require dependency updates. Esp. `django-dynamic-preferences` needs a new release to get the improvements from https://github.com/agateblue/django-dynamic-preferences/pull/287 
Here's what I did:
* `importlib._bootstrap>:283: DeprecationWarning`: the load_module() method is deprecated seems to be caused by reportlabs interal import logic
* `django.utils.timezone.utc` alias is deprecated --> that's the warning caused in dynamic-preferences

Fix test warnings

---

ephios/core/signals.py
ephios/core/templates/core/event_detail.html
ephios/core/templatetags/event_extras.py

I think this change makes the interface more flexible, as receivers can reverse the url themselves or do something else entirely or just not return an action if not appropriate for that event.

Change event_action_signal interface

---

.github/workflows/tests.yml

@jeriox to merge, update the github settings to require the linting pass to succeed with python 3.11 instead of 3.10. Also require the 3.11 tests to pass.

upgrade CI tests to include python3.11

---

.github/workflows/staging.yml

The staging build is using dynamic versioning, but not setting the version correctly:
I'm guessing that's because GH actions only fetches the latest commit by default. So lets fix that!
(see https://github.com/actions/checkout#checkout-v3 )

staging build: fetch all commits

---

ephios/static/ephios/js/main.js

happened when hitting the back button and it was bugging me so hard I fixed it tonight :muscle: 
These were the interesting reads:
* pointing me to the event that worked on pageload: https://christopheraue.net/design/fading-pages-on-load-and-unload
* more info on the page lifecycle and the chrome exclusive APIs if this fix does not work everywhere: https://developer.chrome.com/blog/page-lifecycle-api/
This is related to my comments on #357, but not the initial part about it not working on iOS. Maybe @jeriox can have another look?

PWA: unblur spinner on pageshow

---

ephios/settings.py
ephios/urls.py

configurable env file location

---

ephios/modellogging/log.py

Hmm #978 was insufficient for what I needed to do so I refactored it to this plain old method.

refactor logentry config save hook

---

ephios/core/forms/events.py
ephios/core/signup/methods.py
ephios/core/templates/core/shift_form.html
ephios/core/templates/core/signup_configuration_form.html
ephios/core/views/shift.py
ephios/plugins/basesignup/signup/coupled_signup.py
ephios/plugins/basesignup/signup/no_selfservice.py
ephios/plugins/basesignup/signup/section_based.py
ephios/plugins/basesignup/templates/basesignup/section_based/configuration_form.html

* contains commits of #990 improving/fixing the rendering of the configuration form
* adds horizontal rules around the signup method configuration form to make it visually a little easier to see that section
* when js-loading the configuration form, also pass the shift_id if available so the value of common fields is kept (also when going back to the original method)
* fix a bug where in section-based-signup, sections added could not be removed right again
* fix the link to the signup method documentation
Now after looking at the code again I again thought we need to factor out an `AbstractSignupMethod` from the `BaseSignupMethod` and probably do the same for the config form. The class is way to overloaded.

Signup configuration form improvements

---

docs/development/contributing.rst
ephios/api/templates/api/access_token_reveal.html
ephios/core/models/events.py
ephios/core/models/users.py
ephios/core/signup/participants.py
ephios/core/templates/core/event_list.html
ephios/core/templates/core/settings/settings_notifications.html
ephios/core/templates/core/userprofile_confirm_delete.html
ephios/locale/de/LC_MESSAGES/django.po
ephios/locale/de/LC_MESSAGES/djangojs.po
ephios/modellogging/templates/modellogging/logentry.html
ephios/plugins/guests/models.py
ephios/plugins/pages/models.py
ephios/plugins/pages/templates/pages/page_confirm_delete.html
ephios/plugins/qualification_management/templates/core/qualification_confirm_delete.html
ephios/plugins/qualification_management/templates/core/qualification_form.html
ephios/plugins/simpleresource/models.py
ephios/templates/base.html
ephios/urls.py
poetry.lock
pyproject.toml

Oh boy, I didn't know you had to run `makemessages` with the `djangojs` domain?!
This I think for the most part fixes #830

I18n housekeeping

---

ephios/api/views/events.py
ephios/core/context.py
ephios/core/models/events.py
ephios/core/services/notifications/backends.py
ephios/core/services/notifications/types.py
ephios/core/signup/fallback.py
ephios/core/templates/core/serviceworker.js
ephios/core/urls.py
ephios/core/views/pwa.py
ephios/locale/de/LC_MESSAGES/django.po
ephios/locale/de/LC_MESSAGES/djangojs.po
ephios/settings.py
ephios/static/ephios/js/main.js
ephios/static/ephios/js/serviceworker.js
ephios/static/ephios/scss/ephios_custom.scss
ephios/templates/base.html
ephios/templates/offline.html

This updates the PWA views to class based views and adds a few more fields. Then there are some random fixes and touchups. Biggest change (and the most debatable) is the new serviceworker that caches sites you visit on the go.

PWA more offline availability

---

ephios/core/templates/core/serviceworker.js

PWA Fixups

---

ephios/plugins/pages/models.py
ephios/plugins/pages/views.py

closes #833 
würde dann `slug` als `Kurzform` übersetzen

add help_text to page slug

---

.env.example
docs/admin/deployment/index.rst
ephios/core/apps.py
ephios/core/plugins.py
ephios/settings.py

Add File Logging

---

ephios/api/views/events.py
ephios/core/models/events.py
ephios/locale/de/LC_MESSAGES/django.po
ephios/plugins/basesignup/signup/coupled_signup.py

lets just collect these until we release again

Misc: small fixes and translations before release

---

ephios/settings.py

Why? Because the default `.env` value of `data/static/` meant that if e.g. tests were run from a non `BASE_DIR` working directory django would go look for static files in `ephios/tests/data/static/` which would fail (usally with compressor complaining about not finding some i18n-js-file).

make static root absolute

---

ephios/core/services/notifications/backends.py

Fixes #1077
@dasGoogle you think this would fix it?
may be a quick fix. Adding a second image would be a small effort too

add recipient name to user mails

---

ephios/extra/auth.py

Having these claim names hardcoded is still somewhat hacky. We'd need to change this with the OIDC rework. 
Nextcloud for example only has the full name inside the `name` claim:
https://github.com/H2CK/oidc/wiki/User-Documentation#scopes

dont clear names on missing oidc claims

---

ephios/core/models/events.py
tests/core/test_event_detail.py

```
NoReverseMatch at /
Reverse for 'event_detail' with keyword arguments '{'pk': 69, 'slug': ''}' not found. 1 pattern(s) tried: ['events/(?P<pk>[0-9]+)\\-(?P<slug>[-a-zA-Z0-9_]+)/\\Z']
```

Fix event slug being empty leading to reverse errors

---

ephios/api/access/views.py
ephios/api/urls.py
ephios/plugins/federation/forms.py
ephios/plugins/federation/models.py
ephios/plugins/federation/views/frontend.py
tests/plugins/federation/test_federation_setup.py
tests/plugins/federation/test_federation_views.py

Federation Refactor

---

ephios/api/views/users.py
tests/api/test_user.py

API: Allow dots in email lookup

---

ephios/core/services/notifications/backends.py

self-hosting user had an issue where they marked the email address as invalid in the django-admin interface to disable all notifications for technical reasons while the users should still remain active.

don't send notifications to users with invalid mail address

---

.github/dependabot.yml

I think this would be a great way to reduce dependabot spam while retaining seperate commits for minor/major updates of our libraries.
[Docs for the groups option](https://docs.github.com/en/code-security/dependabot/dependabot-version-updates/configuration-options-for-the-dependabot.yml-file#groups)

group dependabot pip patch updates

---

ephios/settings.py
poetry.lock
pyproject.toml

the recent updates breaks django: https://stackoverflow.com/questions/78977665/django-autoreload-raises-typeerror-unhashable-type-types-simplenamespace
As we only had it for backwards compatibility to python3.8 which is EOL shortly, we can drop it altogether

remove importlib-metadata

---

ephios/core/services/notifications/backends.py

delete user webpush subscription if delivery fails

---

ephios/core/signup/stats.py
ephios/plugins/baseshiftstructures/structure/group_common.py
ephios/plugins/baseshiftstructures/structure/named_teams.py

Fixes #1381. Fixes #1382. 
This is just a quick fix. We're unhappy with the inconsistencies in the assignment, fullness-determination and counts between the signup structures and therefore plan to follow up with a design session (considering all possible combinations and scenarios and what behavior we expect of them), a rewrite of much of the logic touched here and user documentation.
(There is for example another bug affecting the "full"-state for atomic blocks in the complex structure, which can't be fixed without a more thoughtful rewrite of the matching algorithms.)
@lukasrad02 feel free to test this. As we discussed in our call, this should fix the issues you're currently having with your events.

Fix teams structure fullness display

---

ephios/core/templates/core/serviceworker.js
ephios/core/views/auth.py
ephios/core/views/pwa.py
ephios/settings.py
ephios/static/ephios/js/main.js
ephios/templates/base.html

fixes #1400
Decided on varying the cache key depending on the user. The new service worker takes care of deleting the old cache. I'm worried about a new worker not being loaded when logging in via an identity provider though. Can you help me try @jeriox ?

Cycle serviceworker cache on user change

---

docs/user/events/blocks.rst
ephios/api/filters.py
ephios/api/views/events.py
ephios/api/views/users.py
ephios/plugins/federation/views/api.py
ephios/plugins/federation/views/frontend.py

* Fixes a federation bug where event duplicates would show up in the shared list
* adds the option to filter events by start and end time e.g.
`GET /api/events/?start_time__gte=2024-04-01T07%3A00%3A00%2B02%3A00`
* use the same filters for participation

add API time filters

---

ephios/core/templates/core/event_detail.html
ephios/core/templates/core/fragments/event_list_day_mode.html
ephios/core/templates/core/fragments/event_list_list_mode.html
ephios/core/templates/core/home.html
ephios/plugins/federation/templates/federation/external_event_list.html
ephios/static/ephios/scss/ephios_custom.scss

Create  a new eventtype with a long title and you'll see visual glitches on the homepage and the event list, esp. on small screens.
This doesn't make it perfect, but it is an improvement I would say. Please try various event type name lengths and various viewport widths.

eventtype badge visual fixes

---

ephios/core/templates/core/event_detail.html
ephios/core/views/event.py
ephios/extra/permissions.py
ephios/modellogging/recorders.py
ephios/settings.py
tests/core/test_event_detail.py

So that really annoys me: All the `get_perms` and `has_perm` functions, if used with an `obj`, don't seem to regard the non-object permissions. So if a user was in a management group and had general `change_event` permissions without having `change_event` for a particular event, it would never get recognized. This way it does.
Should we built our own version of those functions? Seems complicated to get into sadly: would require us to roll our own `ObjectPermissionChecker` and everything that stems from it :/

fix event change permission check

---

ephios/core/views/shift.py

Closes #1450
When debugging above issue, I noticed that the shift dates are saved in UTC on the server. When rendering the update view, the times are converted into the correct time zone, but the date is not.

Convert shift date into correct timezone

---

ephios/core/forms/events.py
ephios/core/models/events.py
ephios/core/templates/core/event_detail.html
ephios/core/templates/core/fragments/event_list_list_mode.html
ephios/core/templatetags/event_extras.py
ephios/core/views/event.py
ephios/extra/permissions.py
ephios/locale/de/LC_MESSAGES/django.po
ephios/static/ephios/scss/ephios_custom.scss

when testing the bulk actions, it was helpful to have some kind of indicator in the event list list to see what events I am responsible for.
This is what I came up with in a few minutes of tinkering with it.
closes #1258
closes #874

add responsible indicator

---

ephios/modellogging/templates/modellogging/logentry_grouped_list.html

replace p with div

---

ephios/core/views/event.py

`with_show_participant_data_to()` was not applied to the shift participations for the day mode of the event list, thus all participations were redacted.
Fixes #1523

Prefetch participations for day mode of event list

---

poetry.lock
pyproject.toml

upgrades urllib3 to 2.5.0, resolving security issues. Uberspace seems to be fine now.

lift urllib3 version restriction

---

ephios/core/calendar.py
ephios/core/forms/events.py
ephios/core/forms/users.py
ephios/core/management/commands/devdata.py
ephios/core/pdf.py
ephios/core/services/password_reset.py
ephios/core/views/accounts.py
ephios/core/views/auth.py
ephios/core/views/bulk.py
ephios/core/views/event.py
ephios/core/views/eventtype.py
ephios/core/views/settings.py
ephios/core/views/shift.py
ephios/core/views/workinghour.py
ephios/extra/bootstrap.py
ephios/extra/widgets.py
ephios/plugins/federation/forms.py
ephios/plugins/files/forms.py
ephios/plugins/files/signals.py
ephios/plugins/pages/signals.py
ephios/plugins/pages/views.py
ephios/plugins/qualification_management/signals.py
ephios/plugins/simpleresource/forms.py

If it's not lazy, strings specified in class attributes (like success_message on CBVs) are always translated in the default locale (de). `_` should always be the lazy variant to avoid confusion. In placed were it must not be lazy, use an explicit `gettext` instead. I used search to replace occurrences for the wrong import.

underscore should alwasy be gettext_lazy
