ephios-dev/ephios

ephios/event_management/mail.py, ephios/event_management/models.py, ephios/event_management/pdf.py, ephios/user_management/models.py
=> fix PDF display issue, fix rebranding issue

ephios/templates/registration/login.html
=> add password reset link to login view

ephios/user_management/models.py, ephios/user_management/templates/user_management/userprofile_detail.html
=> show qualifications on user profile detail

ephios/event_management/signals.py
=> use concrete sender

.env.example, ephios/settings.py
Test with `./manage.py sendtestmail --admin`
=> fix admin email setting

ephios/event_management/forms.py, ephios/event_management/views.py, ephios/user_management/forms.py
https://stackoverflow.com/questions/51677657/django-queryset-difference-method-not-working
=> use exclude instead of difference

ephios/event_management/mail.py, ephios/event_management/templates/event_management/mails/new_event.html, ephios/user_management/mail.py
=> Event description and location in mail

.pre-commit-config.yaml, ephios/static/ephios/css/main.css
=> fix floating footer on iOS

ephios/user_management/consequences.py, tests/conftest.py, tests/user_management/test_consequences.py
=> fix bug in qualification consequence, add tests for consequences

ephios/event_management/templates/event_management/event_copy.html, ephios/locale/de/LC_MESSAGES/django.po, ephios/user_management/consequences.py
=> translations for v0.2.0

ephios/event_management/templates/event_management/event_form.html, ephios/static/ephios/css/main.css
=> Fix collapsed select2 css

.github/workflows/tests.yml, ephios/core/consequences.py, ephios/core/models/users.py, tests/core/test_consequences.py
Interestingly, some tests fail on those other platforms.
=> CI-test on mysql and postgres

ephios/core/models/events.py, ephios/core/signup/disposition.py, ephios/core/signup/methods.py, ephios/core/templates/core/event_detail.html, ephios/core/templates/core/event_list.html, ephios/core/templates/core/fragments/shift_box_big.html, ephios/core/templatetags/event_extras.py, ephios/core/views/event.py, ephios/extra/context.py, ephios/extra/templatetags/utils.py, ephios/plugins/basesignup/signup/common.py, ephios/plugins/basesignup/signup/instant.py, ephios/plugins/basesignup/signup/request_confirm.py, ephios/plugins/basesignup/signup/section_based.py, ephios/static/ephios/css/main.css, ephios/static/ephios/js/main.js, poetry.lock, pyproject.toml, tests/core/test_setupdata.py, tests/core/test_signup_methods.py
fixes #235 fixes #277 fixes #323
=> Better Event List

ephios/core/templates/core/event_detail.html, ephios/extra/templatetags/rich_text.py
=> use rich_text for event description

ephios/core/dynamic_preferences_registry.py, ephios/core/templates/core/disposition/fragment_participation.html, ephios/core/templates/core/userprofile_list.html, ephios/core/templatetags/user_extras.py, ephios/core/views/accounts.py, ephios/extra/dynamic_preferences_registry.py, ephios/extra/templatetags/utils.py, ephios/plugins/basesignup/templates/basesignup/section_based/fragment_participant.html, ephios/settings.py
=> display qualifications in userlist

ephios/core/models/events.py, ephios/core/pdf.py, ephios/core/signup/disposition.py, ephios/core/templates/core/event_archive.html, ephios/core/templates/core/event_confirm_delete.html, ephios/core/templates/core/event_copy.html, ephios/core/templates/core/event_form.html, ephios/core/templates/core/event_list.html, ephios/core/templates/core/home.html, ephios/core/templates/core/mails/new_event.html, ephios/core/templates/core/shift_confirm_delete.html, ephios/core/templates/core/shift_form.html, ephios/core/urls.py, ephios/core/views/accounts.py, ephios/core/views/bulk.py, ephios/core/views/event.py, ephios/core/views/eventtype.py, ephios/core/views/settings.py, ephios/core/views/shift.py, ephios/core/views/signup.py, ephios/extra/mixins.py, ephios/extra/permissions.py, ephios/plugins/basesignup/signup/section_based.py, ephios/plugins/pages/views.py, tests/core/test_event_form.py, tests/core/test_ical.py, tests/core/test_pdf.py, tests/core/test_views_event.py, tests/plugins/basesignup/test_requestconfirm_signup.py, tests/plugins/basesignup/test_sectionbased_signup.py
=> event slug in url

ephios/core/signup/disposition.py, ephios/core/signup/methods.py, ephios/core/templates/core/disposition/fragment_participation.html, ephios/core/templatetags/user_extras.py, ephios/plugins/basesignup/templates/basesignup/section_based/fragment_participant.html, ephios/plugins/guests/models.py, ephios/static/plugins/basesignup/js/disposition.js, tests/conftest.py, tests/core/test_signup_methods.py
=> add conflicting_shifts signup checker

ephios/core/signup/methods.py, ephios/core/templatetags/user_extras.py, tests/core/test_signup_methods.py
=> Fix can't sign up for back-to-back shifts

ephios/core/templates/core/userprofile_form.html
=> Fix password reset button display

ephios/core/forms/events.py
I only looked at that one file though
=> add some missing translated labels

ephios/plugins/basesignup/signup/section_based.py
=> fix deleting sections

.github/release-drafter.yml, .github/workflows/publish.yml, .github/workflows/release-drafter.yml, .readthedocs.yaml, docs/changelog.rst, docs/conf.py, docs/index.rst, docs/requirements.txt, poetry.lock, pyproject.toml
release-drafter loads the template file from the default branch (aka main). This is why the check is currently failing. It _should_ work once this is merged, but there is no option to test it before.
=> add changelog

ephios/plugins/basesignup/signup/section_based.py, ephios/plugins/basesignup/templates/basesignup/section_based/configuration_form.html, ephios/plugins/basesignup/templates/basesignup/section_based/fragment_state.html
=> add maximum number of participants to section based signup

.github/workflows/staging.yml
I also tried async, but it wasn't pretty so I guess it's better to spend time on a future setup away from uberspace.
=> Staging: ansible pipelining

ephios/core/context.py, ephios/static/plugins/basesignup/js/disposition.js, ephios/templates/base.html
=> fix wrong select2 event, fix missing select2 translations

ephios/core/signup/methods.py, ephios/core/templates/core/event_detail.html, ephios/core/templates/core/shift_form.html, ephios/core/urls.py, ephios/core/views/shift.py, ephios/extra/bootstrap.py, ephios/plugins/basesignup/signals.py, ephios/plugins/basesignup/signup/common.py, ephios/plugins/basesignup/signup/coupled_signup.py, ephios/plugins/basesignup/signup/no_selfservice.py, ephios/static/ephios/js/shift_form.js, tests/plugins/basesignup/test_coupled_signup.py, tests/plugins/basesignup/test_no_selfservice.py
I tried to add `NoSignupAllowed` and the coupled signup described in https://github.com/ephios-dev/ephios/issues/515#issuecomment-883290221.
=> New signup methods

ephios/core/dynamic_preferences_registry.py, ephios/extra/preferences.py
=> remove CustomModelMultipleChoicePreference

ephios/core/signup/disposition.py, ephios/core/templates/core/disposition/disposition.html, tests/plugins/basesignup/test_common.py
=> Disposition: always render requested participations

ephios/settings.py, poetry.lock, pyproject.toml
Doesn't seem to work locally, I haven't figured out how to configure it correctly on my machine.
=> Include html templates in test coverage

.pre-commit-config.yaml, ephios/core/models/events.py, ephios/core/signup/disposition.py
=> fix object collection for bulk deletion

.pre-commit-config.yaml
I got errors when executing them so I ran `pre-commit autoupdate`
=> Precommit tool update

ephios/core/templates/core/disposition/disposition.html, ephios/core/templates/core/event_list.html, ephios/core/templates/core/fragments/approve_consequences.html, ephios/core/templates/core/home.html
=> Restyle home view, some more touchups

ephios/core/views/event.py
I also moved the definition below the list view.
=> Make EventCalendarView have Login Required

.github/dependabot.yml, .github/workflows/codeql-analysis.yml, .github/workflows/publish.yml, .github/workflows/staging.yml, .github/workflows/tests.yml
=> Github-actions update

ephios/core/forms/users.py, ephios/locale/de/LC_MESSAGES/django.po, ephios/static/ephios/js/group_form.js, tests/conftest.py, tests/core/test_event_form.py, tests/core/test_views_group.py
=> Allow users with management permissions to make events visible for all groups

ephios/core/services/notifications/types.py, tests/core/test_event_notifications.py, tests/core/test_notifications.py
=> send CustomEventParticipantNotifications to responsible users

ephios/plugins/simpleresource/forms.py, ephios/plugins/simpleresource/models.py
=> fix wrong media import for DjangoSelect2Widget

ephios/core/templates/core/event_list.html, ephios/core/templatetags/event_extras.py, ephios/core/views/event.py
=> Rework event_list_signup_state_counts filter

ephios/core/forms/users.py, ephios/core/signals.py, ephios/extra/permissions.py, ephios/plugins/pages/signals.py, ephios/plugins/pages/views.py
=> add signal for additional PermissionFields on GroupForm

ephios/core/calendar.py, ephios/core/templates/core/event_detail.html, ephios/core/templates/core/event_list.html, ephios/core/templates/core/fragments/calendar_day.html, ephios/core/templates/core/home.html, ephios/extra/colors.py, ephios/static/ephios/scss/ephios_custom.scss
close #472 
I decided to go for a GCal-styled view:
=> improve calendar layout

ephios/__init__.py, ephios/core/forms/events.py, ephios/core/templates/core/event_list.html, ephios/core/templates/core/home.html, poetry.lock, pyproject.toml
=> Various minor fixes

ephios/core/forms/users.py, ephios/core/models/users.py, tests/core/test_views_userprofile.py
=> Add is_staff to UserForm

.readthedocs.yaml, docs/requirements.txt
see https://docs.readthedocs.io/en/stable/config-file/v2.html#python-version
=> update readthedocs config

ephios/core/views/event.py
A user reported not seeing their shifts in the calendar view. We debugged it together - turns out their mysql server was not giving back the shifts with the `__month` query. This PR replaces it with a datetime query which did resolve the issue for them.
=> Fix month query for some mariadb

ephios/core/consequences.py, tests/plugins/eventautoqualification/test_autoqualification.py
fixes a comparison between naive and aware datetime object
=> Fix crash with auto qualification consequence

ephios/core/dynamic_preferences_registry.py, ephios/core/migrations/0020_qualificationcategory_show_with_user_and_more.py
release after we released the migration in a previous release.
=> remove deprecated qualification preference

ephios/core/services/health/healthchecks.py, ephios/core/templates/core/settings/settings_instance.html, ephios/core/views/healthcheck.py
fixes the diskspace check not being available on windows
=> Unknown healthcheck status

ephios/api/templates/oauth2_provider/application_list.html, ephios/plugins/federation/models.py, ephios/plugins/federation/templates/federation/federation_settings.html
=> Federation: Translation, Modellogging

ephios/core/templates/core/disposition/fragment_participation.html
https://github.com/ephios-dev/ephios/assets/5970076/de74c390-7c77-46dc-b8bf-1b3817154d02
=> Fix disposition collapse

.github/workflows/docker.yml, deployment/compose/docker-compose.yaml, deployment/compose/nginx.conf, docs/admin/deployment/docker/index.rst
=> Checkout docker tags for dynamic versioning

deployment/compose/docker-compose.yaml
this reverts a change I accidentally made in the last docker PR
=> Docker: use "latest" tag in docker-compose.yaml

ephios/api/filters.py, ephios/api/views/users.py, tests/api/test_participation_list.py
=> fix API participation permissions, allow filtering by event type

ephios/core/views/event.py, tests/core/test_event_copy.py
fixes #1250
also, on the day view, show shifts starting until 3 am the next day
=> Fix timezone issues in event copy

ephios/core/templates/core/event_list.html, ephios/core/templates/core/fragments/event_list_add_event_button.html, ephios/core/templates/core/fragments/event_list_day_mode.html, ephios/core/templates/core/fragments/event_list_list_mode.html, ephios/core/views/event.py, ephios/locale/de/LC_MESSAGES/django.po, ephios/plugins/federation/templates/federation/external_event_list.html
=> Fix create event button on empty event list

docs/conf.py
=> insert readthedocs settings

pyproject.toml
https://docs.pypi.org/project_metadata/#icons
=> add more package metadata

docs/conf.py, docs/development/plugins/introduction.rst, docs/requirements.txt, ephios/api/filters.py, ephios/core/context.py, ephios/core/customization.py, ephios/core/pdf.py, ephios/core/plugins.py, ephios/core/signals.py, ephios/core/signup/structure/abstract.py, ephios/core/signup/structure/base.py, ephios/core/templates/core/fragments/attrs.html, ephios/core/templates/core/mails/base.html, ephios/core/templates/core/settings/settings_base.html, ephios/core/templatetags/settings_extras.py, ephios/core/views/auth.py, ephios/core/views/settings.py, ephios/locale/de/LC_MESSAGES/django.po, ephios/plugins/baseshiftstructures/structure/common.py, ephios/plugins/baseshiftstructures/structure/named_teams.py, ephios/plugins/baseshiftstructures/structure/qualification_mix.py, ephios/plugins/complexsignup/structure.py, ephios/plugins/complexsignup/views.py, ephios/plugins/federation/signals.py, ephios/plugins/pages/signals.py, ephios/plugins/qualification_management/signals.py, ephios/settings.py, ephios/templates/base.html, pyproject.toml
=> Interface customization signals

ephios/core/migrations/0030_identityprovider_internal_name_and_more.py, ephios/core/migrations/0031_qualificationgrant_externally_managed_and_more.py, ephios/core/templates/core/userprofile_form.html
=> Bugfix migration for internal name of identity provider

ephios/core/templates/core/fragments/shift_box_big.html, ephios/static/ephios/scss/ephios_printing.scss, ephios/static/ephios/scss/main.scss, ephios/templates/base.html
=> add printing css

ephios/core/signals.py, tests/core/test_nav.py
They don't even warn you about checking permissions that don't exist :cry:
=> Fix groups permission check

ephios/core/services/notifications/types.py, ephios/locale/de/LC_MESSAGES/django.po
I want to improve the wording of these emails.
=> Improve responsible email subject

ephios/plugins/complexsignup/signals.py, ephios/plugins/complexsignup/views.py, ephios/plugins/simpleresource/signals.py
=> add group permission fields to SimpleResource and ComplexSignup

ephios/core/signup/forms.py, ephios/core/signup/structure/abstract.py, ephios/core/templatetags/user_extras.py, ephios/core/views/shift.py, ephios/plugins/complexsignup/templates/complexsignup/configuration_form.html
@jeriox Should we show some warning if there are no blocks?
=> show buildingblock edit link only with permissions

ephios/core/forms/events.py, ephios/core/signup/forms.py, ephios/core/signup/structure/abstract.py, ephios/core/templates/core/event_detail.html, ephios/core/templatetags/user_extras.py, ephios/core/views/event.py, ephios/core/views/shift.py, ephios/plugins/complexsignup/templates/complexsignup/configuration_form.html
based on https://github.com/ephios-dev/ephios/pull/1437
=> make creating user always responsible for event, require change_event for event deletion

ephios/core/templates/core/settings/settings_base.html
=> fix settings nav width

ephios/extra/templatetags/rich_text.py, tests/extra/test_rich_text.py
=> Open external links in new tab

ephios/settings.py, poetry.lock, pyproject.toml
https://docs.djangoproject.com/en/5.1/topics/auth/passwords/#using-argon2-with-django
=> use argon2 as password hasher

ephios/core/signup/fallback.py
=> fix missing template for fallback structure

ephios/locale/de/LC_MESSAGES/django.po
=> adjust translation

ephios/core/calendar.py, ephios/core/forms/users.py, ephios/core/ical.py, ephios/core/models/events.py, ephios/core/services/files.py, ephios/core/templates/core/event_list.html, ephios/core/templates/core/fragments/calendar_day.html, ephios/core/templates/core/logentry_list.html, ephios/core/templates/core/pagination.html, ephios/core/views/auth.py, ephios/core/views/healthcheck.py, ephios/core/views/notifications.py, ephios/core/views/pwa.py, ephios/extra/auth.py, ephios/extra/templatetags/utils.py, ephios/plugins/federation/views/api.py, ephios/plugins/federation/views/frontend.py, ephios/plugins/guests/views.py, ephios/plugins/pages/views.py, ephios/urls.py, poetry.lock, pyproject.toml, tests/core/test_models.py, tests/core/test_views_auth.py
=> upgrade to Django 5.1

ephios/core/services/notifications/types.py
=> use correct timezone for event notifications

ephios/api/views/users.py, tests/api/test_participation_list.py
fixes `bugsink/6bbf1ecd-1efa-4797-954e-154d56702836`
=> fix api own participations queryset

ephios/extra/middleware.py, tests/core/test_notifications.py
=> fix empty notification middleware query param
